kind: Pod
apiVersion: v1
metadata:
  name: init-test

spec:
  initContainers:
    - name: init-cont
      image: busybox:latest
      command: ["sh", "-c", "echo 'Initialization started ...'; sleep 10; echo 'Initialization completed...';"]

  containers:
    - name: main-cont
      image: busybox:latest
      command: ["sh", "-c", "echo 'Main Container created..';"]
