kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devops-practice.ram0403.com
spec:
  group: ram0403.com
  names:
    plural: devops-practice
    singular: prct
    kind: DevOps
    shortNames: 
      - pts
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                duration:
                  type: string
                mode:
                  type: string
                platform:
                  type: string
